shop_site/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<int:p_id>', views.add_to_cart, name='add_to_cart'),
    path('detail/', views.cart_details, name='cart'),
    path('remove:<int:p_id>',views.remove_item,name='remove_item'),
    path('delete:<int:p_id>',views.delete_item,name='delete_item'),

]

shop_site/search/urls.py
from . import views
from django.urls import path

app_name = 'search'
urlpatterns = [
    path('', views.search, name='search')
]

shop_site/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.allProductCategories, name='allproducts'),
    path('<slug:c_slug>/', views.allProductCategories, name='productsbycat'),
    path('<slug:c_slug>/<slug:p_slug>', views.productDetails,name='productdetails' )

]

shop_site/shopping/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_site/cart/models.py
from django.db import models
from shop.models import Product


# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'cart'
        ordering = ['date_added']

    def __str__(self):
        return f"{self.cart_id}"


class CartItems(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'Cart Items'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.name

shop_site/search/models.py
from django.db import models

# Create your models here.

shop_site/shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='categories', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def get_url(self):
        return reverse('shop:productsbycat', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products', blank=True)
    stock = models.IntegerField()
    availability = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def get_url(self):
        return reverse('shop:productdetails', args=[self.category.slug, self.slug])

shop_site/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItems
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_to_cart(request, p_id):
    product = Product.objects.get(id=p_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except ObjectDoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
    cart.save()

    try:
        cart_item = CartItems.objects.get(product=product, cart=cart)
        if cart_item.quantity < product.stock:
            cart_item.quantity += 1
    except ObjectDoesNotExist:
        cart_item = CartItems.objects.create(product=product, cart=cart, quantity=1)
    cart_item.save()
    return redirect('cart:cart')


def cart_details(request, total=0, count=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItems.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            count += cart_item.quantity
    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', dict(cart_items=cart_items,
                                             total=total,
                                             count=count))


def remove_item(request, p_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=p_id)
    cart_item = CartItems.objects.get(product=product, cart=cart)
    if cart_item.quantity > 0:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart')


def delete_item(request,p_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=p_id)
    cart_item = CartItems.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart')

shop_site/search/views.py
from django.shortcuts import render, redirect
from shop.models import Product
from django.db.models import Q


# Create your views here.

def search(request):
    querry = None
    products = None

    if 'q' in request.GET:
        querry = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=querry) | Q(description__contains=querry))
        return render(request, 'search.html', {'querry': querry, 'products': products})

shop_site/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.


def allProductCategories(request, c_slug=None):
    c_page = None
    products_list = None

    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, availability=True)
    else:
        products_list = Product.objects.all().filter(availability=True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(request, 'index.html', {'category': c_page, 'products': products})


def productDetails(request, c_slug, p_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=p_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

shop_site/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/base.css' %}">
    <script src="https://kit.fontawesome.com/c452d0cec6.js" crossorigin="anonymous"></script>
</head>
<body>
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
{% include 'footer.html' %}
</body>
</html>

shop_site/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
your shoppig cart
{% endblock %}

{% block title %}
Cart
{% endblock %}

{% block content %}
<div class="checkout">
    <div class="jumbotron text-center">
        <h1 class="display-4">Your Cart</h1>


        {% if not cart_items %}
        <p class="lead">Your cart is currently empty. Add items to cart to see them here. </p>
        <hr class="my-4">
        <p>Shop from our complete selection</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'shop:allproducts' %}" role="button">Go to shop</a>
        </p>
        {% else %}


        <p class="lead">Your gear is ready to be shipped. </p>
        <hr class="my-4">

        <div class="row">
            <div class="col-md-8">
                <table class="table">
                    <thead class="thead-light table-hover text-center">
                    <tr>
                        <th class="col-5" scope="col">Product</th>
                        <th class="col-2" scope="col">price</th>
                        <th class="col-2" scope="col">quantity</th>
                        <th class="col-2" scope="col">total</th>
                        <th class="col-1" scope="col"></th>

                    </tr>
                    </thead>
                    <tfoot class="text-right">
                    <tr>
                        <td colspan="5">Total<img src="{% static 'images/credits.webp' %}" style="width:5%;">{{total}}
                        </td>
                    </tr>
                    </tfoot>
                    <tbody class="table-body">
                    {% for cart_item in cart_items %}
                    <tr class="table-item">
                        <td class="col-5">
                            <div class="d-flex align-items-center">
                                <a href="{{cart_item.product.get_url}}"><img style="width:80px"
                                                                             class="cart_img"
                                                                             src="{{cart_item.product.image.url}}"
                                                                             alt="..."></a>
                                <div class="cart-title text-start"><a class="text-uppercase text-dark"
                                                                      href="{{cart_item.product.get_url}}"><strong>{{cart_item.product.name}}
                                </strong></a>
                                </div>
                            </div>
                        </td>
                        <td class="col-2"><img src="{% static 'images/credits.webp' %}" style="width:25%;">{{cart_item.product.price}}
                        </td>
                        <td class="col-2">
                            <div class="d-flex align-items-center">
                                <a class="btn btn-items btn-items-increase"
                                   href="{% url 'cart:remove_item' cart_item.product.id %}"><i
                                        class="fa-solid fa-plus"></i></a>
                                {{cart_item.quantity}}
                                <a class="btn btn-items btn-items-decrease"
                                   href=" {% url 'cart:add_to_cart' cart_item.product.id %}"><i
                                        class="fa-solid fa-minus"></i></a>
                            </div>
                        </td>
                        <td class="col-2">{{cart_item.sub_total}}</td>
                        <td colspan="col-1"><a href="{% url 'cart:delete_item' cart_item.product.id %}"><i
                                class="fa-solid fa-xmark"></i></a></td>
                    </tr>
                    {% endfor %}
                    </tbody>

                </table>
            </div>
            <div class="col-md-4">

                <div class="jumbotron summery">
                    <h1 class="display-4">Order summery</h1>

                    <hr class="my-4">
                    <p class="lead">Checkout now or continue shopping</p>
                    TOTAL
                    <p><img src="{% static 'images/credits.webp' %}" style="width:10%;">{{total}}</p>
                    <p class="lead">
                        <a href="{% url 'shop:allproducts' %}" class="btn btn-primary">Continue Shopping</a>
                        <a href="{% url 'shop:allproducts' %}" class="btn btn-secondary">Checkout</a>
                    </p>
                </div>
            </div>
        </div>


        {% endif %}
    </div>

</div>


{% endblock %}

shop_site/templates/footer.html
<footer>
    <p>&copy;kevin.ltd</p>
</footer>

shop_site/templates/header.html
{% load static %}
<header>
    <a href="{% url 'shop:allproducts' %}">

    <img class="logo" src="{% static 'images/logo.svg' %}" alt ="heloo">
        </a>

</header>

shop_site/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
{{ category.description|truncatewords:150 }}
{% else %}
welcome to shop
{% endif %}
{% endblock %}

{% block title %}
{% if category %}
{{ category.name }}

{% else %}
shop here
{% endif %}
{% endblock %}
{% block content %}
{% if category %}
<a href="{% url 'shop:allproducts' %}"></a>
{% endif %}
{% if category %}
<div class="jumbotron jumbotron-fluid" style="background-image:url({{category.image.url}});color:#fff;">
    <div class="container">
        <h1 class="display-4">{{category.name}}</h1>
        <p class="lead">{{category.description}}</p>
    </div>
</div>


{% endif %}
<div class="container">
    <div class="card-deck">
        <div class="row">

            {% for product in products.object_list %}

            <div class="col-md-4 mt-3">
                <div class="card">
                    <a href="{{product.get_url}}">
                        <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p class="card-text"><img src="{% static 'images/Credits.webp' %}" class="cred-img">{{product.price}}
                        </p>
                    </div>
                </div>
            </div>


            {% endfor %}
        </div>
    </div>
    <div>{% if products.paginator.num_pages > 1 %}
        <ul class="pagination pagination-sm justify-content-center">
            {%for pg in products.paginator.page_range %}

            <li class="page-item btn {% if products.number == pg %} active {% endif %} "><a class="page-link"
                                                                                            href="?page={{pg}}">{{pg}}</a>
            </li>
            {% endfor %}

        </ul>
        {% endif %}
    </div>
</div>

{% endblock %}

shop_site/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'shop:allproducts' %}">All Products</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="true">
                    Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for category in links %}
                    <a class="dropdown-item" href="{{category.get_url}}">{{category.name}}</a>
                    <div class="dropdown-divider"></div>
                    {% endfor %}
                </div>
            </li>
            <li class="nav-item">
                <i class="fa-solid fa-cart-shopping fa-xl"></i>
                <a href="{% url 'cart:cart' %}" class="badge badge-dark">
                <span class="badge badge-light">{{count}}</span>
                </a>

            </li>

        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'search:search' %}" method="get">
            {%csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"  name="q">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

shop_site/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{{product.description|truncatewords:150}}
{% endblock %}

{% block title %}
{{product.name}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <img style="width:100%;" src="{{product.image.url}}">
        </div>
        <div class="col-md-6">
            <h1>{{product.name}}</h1>
            <h3><img src="{% static 'images/Credits.webp' %}" class="cred_pro">{{product.price}}</h3>
            {{product.description}}
            {% if product.stock > 0 %}
            <p>
                <a href="{% url 'cart:add_to_cart' product.id %}">
                    <button class="btn">Add to cart</button>
                </a>
                {% else %}
            <h5>
                <p>Out of stock</p>
            </h5>
            {% endif %}
            </p>
        </div>
    </div>


</div>

{% endblock %}

shop_site/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
searchd:{{querry}}
{% endblock %}

{% block title %}
{{querry}}
{% endblock %}
{% block content %}
<div class="container">
    <div class="card-deck">
        <div class="row">

            {% for product in products %}

            <div class="col-md-4 mt-3">
                <div class="card" >
                    <a href="{{product.get_url}}">
                        <img class="card-img-top" src="{{product.image.url}}" alt="Card image cap">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p class="card-text"><img src="{% static 'images/Credits.webp' %}">{{product.price}}</p>
                    </div>
                </div>
            </div>


            {% endfor %}
        </div>
    </div>
    <div>{% if products.paginator.num_pages > 1 %}
        <div class="page_nos">
            {%for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn {% if products.number == pg %} active {% endif %} ">{{pg}}</a>
            {% endfor %}
        </div>

    {% endif %}</div>
</div>

{% endblock %}